-- Inserimento amministratore
INSERT INTO amministratore VALUES (1, 'silvestro', 'admin');
INSERT INTO amministratore VALUES (2, 'daniele', 'admin');
INSERT INTO amministratore VALUES (3, 'filippo', 'admin');

-- Metodo di pagamento contanti
ALTER TABLE metodo_pagamento AUTO_INCREMENT = 1;
INSERT INTO metodo_pagamento (tipo) VALUES ('contanti');

-- Categorie
INSERT INTO categoria (id, animale, tipologia, tipologia_in) VALUES
(1, 'cane', 'cibo', 'secco'),
(2, 'cane', 'cibo', 'secco dietetico'),
(3, 'cane', 'cibo', 'snack'),
(4, 'cane', 'cibo', 'umido'),
(5, 'cane', 'cibo', 'umido dietetico'),
(6, 'cane', 'guinzagliera', 'collari'),
(7, 'cane', 'guinzagliera', 'guinzagli'),
(8, 'cane', 'guinzagliera', 'museruole'),
(9, 'cane', 'guinzagliera', 'pettorine'),
(10, 'cane', 'guinzagliera', 'salvagenti'),
(11, 'cane', 'giochi', 'agility & sport'),
(12, 'cane', 'giochi', 'intelligenti'),
(13, 'cane', 'giochi', 'intrattenimento'),
(14, 'cane', 'igiene', 'casa'),
(15, 'cane', 'igiene', 'mutandine'),
(16, 'cane', 'igiene', 'palette e sacchetti'),
(17, 'cane', 'igiene', 'panni'),
(18, 'cane', 'igiene', 'tappetini igienici'),
(19, 'cane', 'toelettatura', 'asciugamani'),
(20, 'cane', 'toelettatura', 'dentifrici & collutori'),
(21, 'cane', 'toelettatura', 'deodoranti'),
(22, 'cane', 'toelettatura', 'shampoo'),
(23, 'cane', 'toelettatura', 'spazzole'),
(24, 'cane', 'antiparassitari', 'collari'),
(25, 'cane', 'antiparassitari', 'linea naturale'),
(26, 'cane', 'antiparassitari', 'spot-on'),
(27, 'cane', 'antiparassitari', 'spray & polvere'),
(28, 'cane', 'integratori', 'antiansia'),
(29, 'cane', 'integratori', 'condroprotettori'),
(30, 'cane', 'integratori', 'fermenti lattici'),
(31, 'cane', 'integratori', 'multivitaminici'),
(32, 'cane', 'integratori', 'sali minerali'),
(33, 'cane', 'auto', 'comfort'),
(34, 'cane', 'auto', 'coprisedili'),
(35, 'cane', 'auto', 'divisori'),
(36, 'cane', 'auto', 'rampe'),
(37, 'cane', 'cucce & lettini', 'brandine'),
(38, 'cane', 'cucce & lettini', 'cucce esterne'),
(39, 'cane', 'cucce & lettini', 'cucce interne'),
(40, 'cane', 'cucce & lettini', 'cuscini'),
(41, 'cane', 'trasportini', 'borse'),
(42, 'cane', 'trasportini', 'trasportini morbidi'),
(43, 'cane', 'trasportini', 'trasportini rigidi'),
(44, 'cane', 'ciotole', 'accessori'),
(45, 'cane', 'ciotole', 'ciotole'),
(46, 'cane', 'ciotole', 'distributori'),
(47, 'cane', 'abbigliamento', 'cappottini'),
(48, 'cane', 'abbigliamento', 'impermeabili'),
(49, 'cane', 'abbigliamento', 'scarpe'),
(50, 'cane', 'accessori', 'abbigliamento veterinario'),
(51, 'cane', 'accessori', 'porte basculanti'),
(52, 'cane', 'accessori', 'targhe'),
(53, 'gatto', 'cibo', 'secco'),
(54, 'gatto', 'cibo', 'secco dietetico'),
(55, 'gatto', 'cibo', 'snack'),
(56, 'gatto', 'cibo', 'umido'),
(57, 'gatto', 'cibo', 'umido dietetico'),
(58, 'gatto', 'toelettatura', 'asciugamani'),
(59, 'gatto', 'toelettatura', 'dentifrici & collutori'),
(60, 'gatto', 'toelettatura', 'profumi ambienti'),
(61, 'gatto', 'toelettatura', 'shampoo'),
(62, 'gatto', 'toelettatura', 'spazzole'),
(63, 'gatto', 'toelettatura', 'taglia unghie'),
(64, 'gatto', 'antiparassitari', 'collari'),
(65, 'gatto', 'antiparassitari', 'linea naturale'),
(66, 'gatto', 'antiparassitari', 'spot-on'),
(67, 'gatto', 'antiparassitari', 'spray & polvere'),
(68, 'gatto', 'integratori', 'antiansia'),
(69, 'gatto', 'integratori', 'cura del pelo'),
(70, 'gatto', 'integratori', 'fermenti lattici'),
(71, 'gatto', 'integratori', 'multivitaminici'),
(72, 'gatto', 'integratori', 'sali minerali'),
(73, 'gatto', 'tiragraffi', 'arredo'),
(74, 'gatto', 'tiragraffi', 'tappetini'),
(75, 'gatto', 'lettieri', 'accessori'),
(76, 'gatto', 'lettieri', 'agglomeranti'),
(77, 'gatto', 'lettieri', 'cassette'),
(78, 'gatto', 'lettieri', 'non agglomeranti'),
(79, 'gatto', 'lettieri', 'toilette'),
(80, 'gatto', 'igiene', 'casa'),
(81, 'gatto', 'giochi', 'interattivi'),
(82, 'gatto', 'giochi', 'intrattenimento'),
(83, 'gatto', 'giochi', 'tunnel'),
(84, 'gatto', 'guinzagliera', 'collari'),
(85, 'gatto', 'guinzagliera', 'collari fashion'),
(86, 'gatto', 'guinzagliera', 'guinzagli'),
(87, 'gatto', 'ciotole', 'accessori'),
(88, 'gatto', 'ciotole', 'ciotole'),
(89, 'gatto', 'ciotole', 'distributori'),
(90, 'gatto', 'trasportini', 'borse'),
(91, 'gatto', 'trasportini', 'trasportini morbidi'),
(92, 'gatto', 'trasportini', 'trasportini rigidi'),
(93, 'gatto', 'cucce & lettini', 'brandine'),
(94, 'gatto', 'cucce & lettini', 'cucce esterne'),
(95, 'gatto', 'cucce & lettini', 'cucce interne'),
(96, 'gatto', 'cucce & lettini', 'cuscini');


-- Spedizioni
INSERT INTO metodo_spedizione (id, descrizione, prezzo, giorni_consegna_previsti) VALUES (1, 'spedizione standard', 5.99, 3);
INSERT INTO metodo_spedizione (id, descrizione, prezzo, giorni_consegna_previsti) VALUES (2, 'spedizione espressa', 9.99, 1);
INSERT INTO metodo_spedizione (id, descrizione, prezzo) VALUES (3, 'ritiro in sede', 0.00);